#!/bin/bash

role=$1
user=$2
dest=$3
conn=$4

help() {
  echo "Usage: ./gensystemd <role> <user> <destination> [nats-host] [http-port]"
  echo
  echo "Options for <role> include 'server' and 'client'. The destination"
  echo "value should be the path to where the executable and certs live on the"
  echo "remove machine. By default will be value of \$HOME on remote machine."
  echo
  echo "The NATS host will most likely be nats://serveraddr:4222. This is required"
  echo "for the client configuration. The HTTP port is the address/port the HTTP"
  echo "server should bind to. The default is ':3000'."
}

assert() {
  label=$1
  value=$2

  if [ -z "$value" ]; then
    echo "Error: $label is required"
    echo
    help
    exit 1
  fi
}

case "$role" in
  server)
    if [ -z "$conn" ]; then
      conn=":3000"
    fi

    assert "user" "$user"
    assert "destination" "$dest"
    execstart="$dest/diceshaker -role server -listen $conn -certfile $dest/cert.pem -keyfile $dest/key.pem"
    ;;

  client)
    assert "user" "$user"
    assert "destination" "$dest"
    assert "nats host" "$conn"
    execstart="$dest/diceshaker -role client -connect $conn -certfile $dest/cert.pem -keyfile $dest/key.pem"
    ;;

  help|-h|--help)
    help
    exit 0
    ;;

  *)
    assert "role"
    ;;
esac

cat <<-HERE
[Unit]
Description=Diceshaker client application
Documentation=https://github.com/minond/diceshaker
After=network-online.target multi-user.target
Wants=network-online.target multi-user.target
Requires=network-online.target

[Service]
Type=simple
User=$user
WorkingDirectory=$dest
ExecStart=$execstart
ExecReload=/bin/kill -s HUP \$MAINPID
KillMode=process
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
HERE
